// AUTO-GENERATED BY scripts/fetch_all_india_schemes.py
// Do not edit manually. Generated on Thu  3 Sep 04:42:29 UTC 2026

import { Scheme } from '../types';

export const ALL_INDIA_SCHEMES: Scheme[] = [
  {
    "id": "pm-kisan",
    "name": "PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)",
    "nativeName": "\u0baa\u0bbf\u0bb0\u0ba4\u0bae\u0bb0\u0bcd \u0b95\u0bbf\u0b9a\u0bbe\u0ba9\u0bcd \u0b9a\u0bae\u0bcd\u0bae\u0bbe\u0ba9\u0bcd \u0ba8\u0bbf\u0ba4\u0bbf / \u0d2a\u0d3f.\u0d0e\u0d02. \u0d15\u0d3f\u0d38\u0d3e\u0d7b \u0d38\u0d2e\u0d4d\u0d2e\u0d3e\u0d7b \u0d28\u0d3f\u0d27\u0d3f",
    "authority": "Ministry of Agriculture and Farmers Welfare",
    "department": "Agriculture & Farmers Welfare",
    "schemeType": "central",
    "stateId": "ALL",
    "state": "All India",
    "category": "agriculture",
    "summarySimple": "Provides \u20b96,000 per year in 3 equal installments of \u20b92,000 directly into bank accounts of landholding farmer families.",
    "benefits": {
      "amount": "\u20b96,000 / year",
      "frequency": "Three equal installments of \u20b92,000 every 4 months",
      "type": "cash_transfer",
      "shortSummary": "Direct cash assistance of \u20b96,000 annually via Aadhaar DBT",
      "detailedBenefit": "Direct income support transferred straight into the Aadhaar-seeded bank account of eligible small and marginal farmer families."
    },
    "eligibility": {
      "allowedOccupations": [
        "farmer",
        "agriculture"
      ],
      "requiresLandHoldingMaxAcres": 5.0,
      "applicableStates": [
        "ALL"
      ],
      "targetCategories": [
        "agriculture"
      ]
    },
    "documents": [
      {
        "id": "doc-aadhaar",
        "name": "Aadhaar Card",
        "isMandatory": true,
        "description": "Mandatory identity proof linked with mobile number for e-KYC"
      },
      {
        "id": "doc-land",
        "name": "Land Ownership Record (Patta / Chitta / RoR)",
        "isMandatory": true,
        "description": "Proof of agricultural landholding in applicant's name"
      },
      {
        "id": "doc-bank",
        "name": "Bank Passbook",
        "isMandatory": true,
        "description": "Aadhaar-linked active bank account with IFSC code"
      }
    ],
    "applicationSteps": [
      "Visit the official PM-KISAN portal (https://pmkisan.gov.in) or visit your nearest CSC / e-Sevai centre.",
      "Click on 'New Farmer Registration' and enter your Aadhaar Number and State.",
      "Fill in landholding details (survey number, patta number, area in hectares/acres).",
      "Submit and complete OTP-based or biometric e-KYC."
    ],
    "applicationUrl": "https://pmkisan.gov.in",
    "offlineApplicationCenter": "Village Administrative Officer (VAO) / Agriculture Department / CSC Center",
    "officialSource": "https://pmkisan.gov.in",
    "lastVerified": "2026-09-01",
    "verifiedStatus": "VERIFIED_OFFICIAL"
  },
  {
    "id": "pm-awas-gramin",
    "name": "Pradhan Mantri Awas Yojana - Gramin (PMAY-G)",
    "nativeName": "\u0baa\u0bbf\u0bb0\u0ba4\u0bae\u0bb0\u0bcd \u0b8a\u0bb0\u0b95 \u0bb5\u0bc0\u0b9f\u0bcd\u0b9f\u0bc1\u0bb5\u0b9a\u0ba4\u0bbf \u0ba4\u0bbf\u0b9f\u0bcd\u0b9f\u0bae\u0bcd / \u0d2a\u0d3f.\u0d0e\u0d02. \u0d06\u0d35\u0d3e\u0d38\u0d4d \u0d2f\u0d4b\u0d1c\u0d28 (\u0d17\u0d4d\u0d30\u0d3e\u0d2e\u0d40\u0d7a)",
    "authority": "Ministry of Rural Development",
    "department": "Rural Housing",
    "schemeType": "central",
    "stateId": "ALL",
    "state": "All India",
    "category": "housing",
    "summarySimple": "Financial assistance of \u20b91.20 Lakh to \u20b91.30 Lakh for construction of a permanent pucca house with basic amenities.",
    "benefits": {
      "amount": "\u20b91,20,000 to \u20b91,30,000",
      "frequency": "Milestone-based installments linked to geo-tagged construction progress",
      "type": "subsidy",
      "shortSummary": "Direct financial aid up to \u20b91.3 Lakh for building a pucca house",
      "detailedBenefit": "Financial grant for building a safe, permanent house with toilet provision and 90-95 days of unskilled labour support under MGNREGS."
    },
    "eligibility": {
      "maxAnnualIncome": 150000,
      "applicableStates": [
        "ALL"
      ],
      "targetCategories": [
        "housing"
      ]
    },
    "documents": [
      {
        "id": "doc-aadhaar",
        "name": "Aadhaar Card",
        "isMandatory": true,
        "description": "Identity proof of all adult family members"
      },
      {
        "id": "doc-ration",
        "name": "Ration Card (BPL / SECC)",
        "isMandatory": true,
        "description": "Proof of inclusion in rural deprivation list"
      },
      {
        "id": "doc-bank",
        "name": "Bank Passbook",
        "isMandatory": true,
        "description": "Bank account details for DBT fund disbursement"
      }
    ],
    "applicationSteps": [
      "Contact your Gram Panchayat Secretary or Village Administrative Officer.",
      "Verify your household status in the PMAY-G Beneficiary Awaas+ list.",
      "Submit bank details and land clearance for geo-tagging approval."
    ],
    "applicationUrl": "https://pmayg.nic.in",
    "offlineApplicationCenter": "Gram Panchayat Office / Block Development Office (BDO)",
    "officialSource": "https://pmayg.nic.in",
    "lastVerified": "2026-09-01",
    "verifiedStatus": "VERIFIED_OFFICIAL"
  },
  {
    "id": "ayushman-bharat-pmjay",
    "name": "Ayushman Bharat - PM-JAY (Pradhan Mantri Jan Arogya Yojana)",
    "nativeName": "\u0b86\u0baf\u0bc1\u0bb7\u0bcd\u0bae\u0bbe\u0ba9\u0bcd \u0baa\u0bbe\u0bb0\u0ba4\u0bcd \u0bae\u0bb0\u0bc1\u0ba4\u0bcd\u0ba4\u0bc1\u0bb5\u0b95\u0bcd \u0b95\u0bbe\u0baa\u0bcd\u0baa\u0bc0\u0b9f\u0bc1 / \u0d06\u0d2f\u0d41\u0d37\u0d4d\u0d2e\u0d3e\u0d7b \u0d2d\u0d3e\u0d30\u0d24\u0d4d \u0d2a\u0d4d\u0d30\u0d27\u0d3e\u0d28\u0d2e\u0d28\u0d4d\u0d24\u0d4d\u0d30\u0d3f \u0d1c\u0d7b \u0d06\u0d30\u0d4b\u0d17\u0d4d\u0d2f \u0d2f\u0d4b\u0d1c\u0d28",
    "authority": "National Health Authority",
    "department": "Health and Family Welfare",
    "schemeType": "central",
    "stateId": "ALL",
    "state": "All India",
    "category": "health",
    "summarySimple": "Free health insurance coverage up to \u20b95,00,000 per family per year for secondary and tertiary cashless hospitalization.",
    "benefits": {
      "amount": "\u20b95,00,000 / family / year",
      "frequency": "Cashless hospitalization coverage per family annually",
      "type": "insurance",
      "shortSummary": "Cashless medical treatment up to \u20b95 Lakh annually in empaneled hospitals",
      "detailedBenefit": "Covers medical exams, treatment, surgery, post-hospitalization expenses, and medicines across over 27,000 empaneled hospitals nationwide."
    },
    "eligibility": {
      "maxAnnualIncome": 250000,
      "applicableStates": [
        "ALL"
      ],
      "targetCategories": [
        "health"
      ]
    },
    "documents": [
      {
        "id": "doc-aadhaar",
        "name": "Aadhaar Card",
        "isMandatory": true,
        "description": "Identity proof of beneficiary"
      },
      {
        "id": "doc-ration",
        "name": "Ration Card",
        "isMandatory": true,
        "description": "Family card identifying member eligibility"
      }
    ],
    "applicationSteps": [
      "Visit any empaneled government or private hospital or nearest CSC centre.",
      "Meet the 'Ayushman Mitra' at the helpdesk.",
      "Provide Aadhaar card and Ration card to verify eligibility and generate your Ayushman Golden Card instantly."
    ],
    "applicationUrl": "https://pmjay.gov.in",
    "offlineApplicationCenter": "Any Empaneled Government / Private Hospital or CSC Center",
    "officialSource": "https://pmjay.gov.in",
    "lastVerified": "2026-09-01",
    "verifiedStatus": "VERIFIED_OFFICIAL"
  },
  {
    "id": "pm-svanidhi",
    "name": "PM SVANidhi (Street Vendor's AtmaNirbhar Nidhi)",
    "nativeName": "\u0baa\u0bbf\u0bb0\u0ba4\u0bae\u0bb0\u0bcd \u0ba4\u0bc6\u0bb0\u0bc1\u0bb5\u0bcb\u0bb0 \u0bb5\u0bbf\u0baf\u0bbe\u0baa\u0bbe\u0bb0\u0bbf\u0b95\u0bb3\u0bcd \u0b95\u0b9f\u0ba9\u0bcd \u0ba4\u0bbf\u0b9f\u0bcd\u0b9f\u0bae\u0bcd / \u0d2a\u0d3f.\u0d0e\u0d02. \u0d38\u0d4d\u0d35\u0d28\u0d3f\u0d27\u0d3f",
    "authority": "Ministry of Housing and Urban Affairs",
    "department": "Urban Livelihoods",
    "schemeType": "central",
    "stateId": "ALL",
    "state": "All India",
    "category": "business",
    "summarySimple": "Collateral-free working capital micro-loans of \u20b910,000 to \u20b950,000 with 7% interest subsidy for street vendors and small traders.",
    "benefits": {
      "amount": "\u20b910,000 (1st Tranche), \u20b920,000 (2nd), \u20b950,000 (3rd)",
      "frequency": "Progressive tranches upon timely digital repayments",
      "type": "loan",
      "shortSummary": "Collateral-free working capital loan up to \u20b950,000 with 7% interest rebate",
      "detailedBenefit": "Empowers urban and peri-urban vendors to resume and expand their micro-businesses with low-interest institutional bank credit."
    },
    "eligibility": {
      "allowedOccupations": [
        "business",
        "vendor",
        "worker"
      ],
      "applicableStates": [
        "ALL"
      ],
      "targetCategories": [
        "business",
        "financial"
      ]
    },
    "documents": [
      {
        "id": "doc-aadhaar",
        "name": "Aadhaar Card",
        "isMandatory": true,
        "description": "Identity proof"
      },
      {
        "id": "doc-vendor",
        "name": "Certificate of Vending / ID Card",
        "isMandatory": true,
        "description": "Issued by Urban Local Body / Municipality or Letter of Recommendation"
      },
      {
        "id": "doc-bank",
        "name": "Bank Account details",
        "isMandatory": true,
        "description": "Account where loan funds will be disbursed"
      }
    ],
    "applicationSteps": [
      "Visit the PM SVANidhi portal (https://pmsvanidhi.mohua.gov.in) or your Municipality Office.",
      "Select your Urban Local Body and provide your Vending Certificate number.",
      "Choose a preferred lending bank and submit your application."
    ],
    "applicationUrl": "https://pmsvanidhi.mohua.gov.in",
    "offlineApplicationCenter": "Town Vending Committee / Municipal Corporation / Nationalized Banks",
    "officialSource": "https://pmsvanidhi.mohua.gov.in",
    "lastVerified": "2026-09-01",
    "verifiedStatus": "VERIFIED_OFFICIAL"
  },
  {
    "id": "pm-vishwakarma",
    "name": "PM Vishwakarma Scheme",
    "nativeName": "\u0baa\u0bbf\u0bb0\u0ba4\u0bae\u0bb0\u0bcd \u0bb5\u0bbf\u0bb8\u0bcd\u0bb5\u0b95\u0bb0\u0bcd\u0bae\u0bbe \u0ba4\u0bbf\u0b9f\u0bcd\u0b9f\u0bae\u0bcd / \u0d2a\u0d3f.\u0d0e\u0d02. \u0d35\u0d3f\u0d36\u0d4d\u0d35\u0d15\u0d7c\u0d2e \u0d2f\u0d4b\u0d1c\u0d28",
    "authority": "Ministry of Micro, Small and Medium Enterprises",
    "department": "MSME",
    "schemeType": "central",
    "stateId": "ALL",
    "state": "All India",
    "category": "employment",
    "summarySimple": "Holistic support for traditional artisans & craftspeople: \u20b915,000 toolkit grant, 5-7 days skill training with \u20b9500/day stipend, and up to \u20b93 Lakh loan at 5% interest.",
    "benefits": {
      "amount": "\u20b915,000 toolkit + \u20b93,00,000 collateral-free loan at 5% interest",
      "frequency": "One-time toolkit voucher + credit tranches",
      "type": "subsidy",
      "shortSummary": "\u20b915,000 modern toolkit incentive + low interest business loans",
      "detailedBenefit": "Recognition via PM Vishwakarma Certificate, skill upgradation stipend, modern tool grant, and collateral-free enterprise loan."
    },
    "eligibility": {
      "minAge": 18,
      "allowedOccupations": [
        "worker",
        "artisan",
        "business"
      ],
      "applicableStates": [
        "ALL"
      ],
      "targetCategories": [
        "employment",
        "business"
      ]
    },
    "documents": [
      {
        "id": "doc-aadhaar",
        "name": "Aadhaar Card",
        "isMandatory": true,
        "description": "Identity and biometric authentication"
      },
      {
        "id": "doc-bank",
        "name": "Bank Passbook",
        "isMandatory": true,
        "description": "Bank account details"
      },
      {
        "id": "doc-trade",
        "name": "Self-Declaration of Trade",
        "isMandatory": true,
        "description": "Declaration of engaging in one of 18 traditional family trades"
      }
    ],
    "applicationSteps": [
      "Visit the official PM Vishwakarma portal (https://pmvishwakarma.gov.in) via Common Service Centre (CSC).",
      "Complete Aadhaar biometric verification and select your registered trade (e.g. Carpenter, Blacksmith, Sculptor, Cobbler, Tailor).",
      "Submit for Gram Panchayat / Urban Local Body verification."
    ],
    "applicationUrl": "https://pmvishwakarma.gov.in",
    "offlineApplicationCenter": "Common Service Centre (CSC) / District Industries Centre (DIC)",
    "officialSource": "https://pmvishwakarma.gov.in",
    "lastVerified": "2026-09-01",
    "verifiedStatus": "VERIFIED_OFFICIAL"
  },
  {
    "id": "atal-pension-yojana",
    "name": "Atal Pension Yojana (APY)",
    "nativeName": "\u0b85\u0b9f\u0bb2\u0bcd \u0b93\u0baf\u0bcd\u0bb5\u0bc2\u0ba4\u0bbf\u0baf\u0ba4\u0bcd \u0ba4\u0bbf\u0b9f\u0bcd\u0b9f\u0bae\u0bcd / \u0d05\u0d1f\u0d7d \u0d2a\u0d46\u0d7b\u0d37\u0d7b \u0d2f\u0d4b\u0d1c\u0d28",
    "authority": "Pension Fund Regulatory and Development Authority (PFRDA)",
    "department": "Financial Services",
    "schemeType": "central",
    "stateId": "ALL",
    "state": "All India",
    "category": "senior_citizens",
    "summarySimple": "Guaranteed monthly pension of \u20b91,000, \u20b92,000, \u20b93,000, \u20b94,000, or \u20b95,000 from age 60 for unorganized sector workers.",
    "benefits": {
      "amount": "\u20b91,000 to \u20b95,000 / month",
      "frequency": "Guaranteed monthly lifelong pension after 60 years of age",
      "type": "pension",
      "shortSummary": "Guaranteed lifelong monthly pension after age 60",
      "detailedBenefit": "Provides lifelong social security pension to subscriber and spouse, with return of accumulated pension corpus to nominee after demise."
    },
    "eligibility": {
      "minAge": 18,
      "maxAge": 40,
      "applicableStates": [
        "ALL"
      ],
      "targetCategories": [
        "senior_citizens",
        "financial"
      ]
    },
    "documents": [
      {
        "id": "doc-aadhaar",
        "name": "Aadhaar Card",
        "isMandatory": true,
        "description": "Identity proof"
      },
      {
        "id": "doc-bank",
        "name": "Savings Bank Account",
        "isMandatory": true,
        "description": "Account with auto-debit facility for monthly contribution"
      }
    ],
    "applicationSteps": [
      "Visit your savings bank branch or Post Office where you have an active account.",
      "Fill out the APY registration form specifying your desired monthly pension amount (\u20b91,000 to \u20b95,000).",
      "Ensure sufficient balance in your bank account for monthly auto-debit."
    ],
    "applicationUrl": "https://www.npscra.nsdl.co.in",
    "offlineApplicationCenter": "Any Commercial Bank / Post Office Branch",
    "officialSource": "https://www.npscra.nsdl.co.in",
    "lastVerified": "2026-09-01",
    "verifiedStatus": "VERIFIED_OFFICIAL"
  },
  {
    "id": "tn-magalir-urimai",
    "name": "Kalaignar Magalir Urimai Thittam",
    "nativeName": "\u0b95\u0bb2\u0bc8\u0b9e\u0bb0\u0bcd \u0bae\u0b95\u0bb3\u0bbf\u0bb0\u0bcd \u0b89\u0bb0\u0bbf\u0bae\u0bc8\u0ba4\u0bcd \u0ba4\u0bbf\u0b9f\u0bcd\u0b9f\u0bae\u0bcd",
    "authority": "Government of Tamil Nadu",
    "department": "Special Programme Implementation",
    "schemeType": "state",
    "stateId": "TN",
    "state": "Tamil Nadu",
    "category": "women",
    "summarySimple": "Monthly basic income grant of \u20b91,000 transferred directly into the bank accounts of women heads of households in Tamil Nadu.",
    "benefits": {
      "amount": "\u20b91,000 / month (\u20b912,000 / year)",
      "frequency": "Monthly direct benefit transfer on the 15th of every month",
      "type": "cash_transfer",
      "shortSummary": "\u20b91,000 monthly cash assistance directly to women family heads",
      "detailedBenefit": "Empowers women family heads with independent financial dignity, social security, and direct economic support."
    },
    "eligibility": {
      "minAge": 21,
      "targetGenders": [
        "female"
      ],
      "maxAnnualIncome": 250000,
      "requiresLandHoldingMaxAcres": 5.0,
      "applicableStates": [
        "TN"
      ],
      "targetCategories": [
        "women",
        "financial"
      ]
    },
    "documents": [
      {
        "id": "doc-ration",
        "name": "Smart Family Card (Ration Card)",
        "isMandatory": true,
        "description": "Tamil Nadu digital smart ration card indicating woman as family head"
      },
      {
        "id": "doc-aadhaar",
        "name": "Aadhaar Card",
        "isMandatory": true,
        "description": "Applicant's biometric identity proof"
      },
      {
        "id": "doc-eb",
        "name": "Electricity Consumer Number",
        "isMandatory": true,
        "description": "Household electricity card indicating annual usage below 3600 units"
      },
      {
        "id": "doc-bank",
        "name": "Bank Passbook",
        "isMandatory": true,
        "description": "Aadhaar-linked active savings account"
      }
    ],
    "applicationSteps": [
      "Obtain the special application form distributed at your local ration shop / ward camp.",
      "Attend the designated Kalaignar Magalir Urimai special camp in your revenue ward.",
      "Provide Smart Ration card and biometric Aadhaar authentication."
    ],
    "applicationUrl": "https://kmut.tn.gov.in",
    "offlineApplicationCenter": "Revenue Ward Camp / e-Sevai Centre / Taluk Office",
    "officialSource": "https://kmut.tn.gov.in",
    "lastVerified": "2026-09-01",
    "verifiedStatus": "VERIFIED_OFFICIAL"
  },
  {
    "id": "tn-pudhumai-penn",
    "name": "Pudhumai Penn Thittam (Moovalur Ramamirtham Higher Education)",
    "nativeName": "\u0baa\u0bc1\u0ba4\u0bc1\u0bae\u0bc8\u0baa\u0bcd \u0baa\u0bc6\u0ba3\u0bcd \u0ba4\u0bbf\u0b9f\u0bcd\u0b9f\u0bae\u0bcd (\u0bae\u0bc2\u0bb5\u0bb2\u0bc2\u0bb0\u0bcd \u0bb0\u0bbe\u0bae\u0bbe\u0bae\u0bbf\u0bb0\u0bcd\u0ba4\u0bae\u0bcd \u0b89\u0baf\u0bb0\u0bcd\u0b95\u0bb2\u0bcd\u0bb5\u0bbf\u0ba4\u0bcd \u0ba4\u0bbf\u0b9f\u0bcd\u0b9f\u0bae\u0bcd)",
    "authority": "Social Welfare and Women Empowerment Department",
    "department": "Social Welfare",
    "schemeType": "state",
    "stateId": "TN",
    "state": "Tamil Nadu",
    "category": "education",
    "summarySimple": "\u20b91,000 per month financial aid for female students from government schools pursuing higher education degrees, diplomas, or ITI courses.",
    "benefits": {
      "amount": "\u20b91,000 / month",
      "frequency": "Monthly credit throughout undergraduate degree/diploma duration",
      "type": "scholarship",
      "shortSummary": "\u20b91,000 monthly allowance for girl students during higher education",
      "detailedBenefit": "Aims to prevent female dropout, reduce early marriage, and increase higher education enrollment ratio among girls."
    },
    "eligibility": {
      "minAge": 17,
      "maxAge": 25,
      "targetGenders": [
        "female"
      ],
      "requiresStudent": true,
      "applicableStates": [
        "TN"
      ],
      "targetCategories": [
        "education",
        "women"
      ]
    },
    "documents": [
      {
        "id": "doc-school-tc",
        "name": "School Study Certificate (Classes 6 to 12)",
        "isMandatory": true,
        "description": "Certificate showing continuous study in Tamil Nadu government schools"
      },
      {
        "id": "doc-college-id",
        "name": "College Admission Proof / ID",
        "isMandatory": true,
        "description": "Proof of current enrollment in recognized college / polytechnic / ITI"
      },
      {
        "id": "doc-aadhaar",
        "name": "Aadhaar Card",
        "isMandatory": true,
        "description": "Student's identity proof"
      },
      {
        "id": "doc-bank",
        "name": "Student Bank Account Passbook",
        "isMandatory": true,
        "description": "Bank account opened in student's name"
      }
    ],
    "applicationSteps": [
      "Approach your college Nodal Officer / Principal's office during first semester enrollment.",
      "Submit details through the Pudhumai Penn institutional portal verification.",
      "Once verified by the Social Welfare Department, funds are credited monthly via Aadhaar DBT."
    ],
    "applicationUrl": "https://www.pudhumaipenn.tn.gov.in",
    "offlineApplicationCenter": "College Student Welfare Section / District Social Welfare Office",
    "officialSource": "https://www.pudhumaipenn.tn.gov.in",
    "lastVerified": "2026-09-01",
    "verifiedStatus": "VERIFIED_OFFICIAL"
  },
  {
    "id": "tn-thamizh-pudhalvan",
    "name": "Thamizh Pudhalvan Thittam",
    "nativeName": "\u0ba4\u0bae\u0bbf\u0bb4\u0bcd\u0baa\u0bcd \u0baa\u0bc1\u0ba4\u0bb2\u0bcd\u0bb5\u0ba9\u0bcd \u0ba4\u0bbf\u0b9f\u0bcd\u0b9f\u0bae\u0bcd",
    "authority": "Department of Higher Education",
    "department": "Higher Education",
    "schemeType": "state",
    "stateId": "TN",
    "state": "Tamil Nadu",
    "category": "education",
    "summarySimple": "\u20b91,000 per month financial assistance for boy students who studied in Tamil Nadu government schools (Classes 6 to 12) pursuing higher education.",
    "benefits": {
      "amount": "\u20b91,000 / month",
      "frequency": "Monthly direct benefit transfer throughout higher studies",
      "type": "scholarship",
      "shortSummary": "\u20b91,000 monthly allowance for boy students pursuing college/diploma",
      "detailedBenefit": "Direct financial incentive to encourage boys from economically weaker families to complete collegiate degrees, polytechnics, or ITI."
    },
    "eligibility": {
      "minAge": 17,
      "maxAge": 25,
      "targetGenders": [
        "male"
      ],
      "requiresStudent": true,
      "applicableStates": [
        "TN"
      ],
      "targetCategories": [
        "education",
        "employment"
      ]
    },
    "documents": [
      {
        "id": "doc-school-cert",
        "name": "Government School Study Certificate (6th to 12th)",
        "isMandatory": true,
        "description": "Certificate from headmaster verifying government school education"
      },
      {
        "id": "doc-college-bonafide",
        "name": "College Bonafide Certificate",
        "isMandatory": true,
        "description": "Proof of active college enrollment"
      },
      {
        "id": "doc-aadhaar",
        "name": "Aadhaar Card",
        "isMandatory": true,
        "description": "Aadhaar number of student"
      },
      {
        "id": "doc-bank",
        "name": "Student Bank Passbook",
        "isMandatory": true,
        "description": "Direct bank account for monthly DBT"
      }
    ],
    "applicationSteps": [
      "Register through your college admission desk and upload EMIS school certificate.",
      "Verify bank account seeded with Aadhaar.",
      "College principal approves list on the state higher education portal."
    ],
    "applicationUrl": "https://www.tn.gov.in",
    "offlineApplicationCenter": "College Admission / Nodal Officer Desk",
    "officialSource": "https://www.tn.gov.in",
    "lastVerified": "2026-09-01",
    "verifiedStatus": "VERIFIED_OFFICIAL"
  },
  {
    "id": "tn-cmchis",
    "name": "Chief Minister's Comprehensive Health Insurance Scheme (CMCHIS)",
    "nativeName": "\u0bae\u0bc1\u0ba4\u0bb2\u0bae\u0bc8\u0b9a\u0bcd\u0b9a\u0bb0\u0bbf\u0ba9\u0bcd \u0bb5\u0bbf\u0bb0\u0bbf\u0bb5\u0bbe\u0ba9 \u0bae\u0bb0\u0bc1\u0ba4\u0bcd\u0ba4\u0bc1\u0bb5\u0b95\u0bcd \u0b95\u0bbe\u0baa\u0bcd\u0baa\u0bc0\u0b9f\u0bcd\u0b9f\u0bc1\u0ba4\u0bcd \u0ba4\u0bbf\u0b9f\u0bcd\u0b9f\u0bae\u0bcd",
    "authority": "United India Insurance / Tamil Nadu Health Systems Project",
    "department": "Health and Family Welfare",
    "schemeType": "state",
    "stateId": "TN",
    "state": "Tamil Nadu",
    "category": "health",
    "summarySimple": "Cashless medical insurance coverage up to \u20b95,00,000 per family per year for over 1,090 surgical procedures and medical treatments.",
    "benefits": {
      "amount": "\u20b95,00,000 / year",
      "frequency": "Cashless hospitalization coverage per family annually",
      "type": "insurance",
      "shortSummary": "Cashless treatment up to \u20b95 Lakh in empaneled hospitals across TN",
      "detailedBenefit": "Provides 100% cashless medical coverage, diagnostics, surgery, and intensive care across government and private empaneled hospitals."
    },
    "eligibility": {
      "maxAnnualIncome": 120000,
      "applicableStates": [
        "TN"
      ],
      "targetCategories": [
        "health"
      ]
    },
    "documents": [
      {
        "id": "doc-ration",
        "name": "Smart Ration Card",
        "isMandatory": true,
        "description": "Tamil Nadu Smart Family Card"
      },
      {
        "id": "doc-income",
        "name": "Income Certificate",
        "isMandatory": true,
        "description": "Revenue department certificate showing annual income below \u20b91.2 Lakh"
      },
      {
        "id": "doc-aadhaar",
        "name": "Aadhaar Card",
        "isMandatory": true,
        "description": "Identity proof of all family members"
      }
    ],
    "applicationSteps": [
      "Visit the CMCHIS kiosk at your District Collectorate or Government Headquarters Hospital.",
      "Submit Smart Ration card, Income Certificate, and Aadhaar card.",
      "Get your biometric photo captured and receive your CMCHIS Smart Card on the spot."
    ],
    "applicationUrl": "https://cmchistn.com",
    "offlineApplicationCenter": "District Collectorate CMCHIS Kiosk / Govt Hospital Helpdesk",
    "officialSource": "https://cmchistn.com",
    "lastVerified": "2026-09-01",
    "verifiedStatus": "VERIFIED_OFFICIAL"
  },
  {
    "id": "kl-life-mission",
    "name": "LIFE Mission Housing Scheme (Livelihood Inclusion and Financial Empowerment)",
    "nativeName": "\u0d32\u0d48\u0d2b\u0d4d \u0d2e\u0d3f\u0d37\u0d7b \u0d2d\u0d35\u0d28 \u0d28\u0d3f\u0d7c\u0d2e\u0d4d\u0d2e\u0d3e\u0d23 \u0d2a\u0d26\u0d4d\u0d27\u0d24\u0d3f",
    "authority": "Local Self Government Department, Government of Kerala",
    "department": "LSGD Kerala",
    "schemeType": "state",
    "stateId": "KL",
    "state": "Kerala",
    "category": "housing",
    "summarySimple": "Financial assistance of \u20b94,00,000 to construct safe, secure permanent houses for homeless and landless families across Kerala.",
    "benefits": {
      "amount": "\u20b94,00,000",
      "frequency": "4 staged installments linked to construction milestones (Basement, Lintel, Roof, Completion)",
      "type": "subsidy",
      "shortSummary": "\u20b94 Lakh financial assistance for building a permanent home",
      "detailedBenefit": "Comprehensive housing and livelihood inclusion package providing financial grant to construct durable pucca homes."
    },
    "eligibility": {
      "maxAnnualIncome": 100000,
      "applicableStates": [
        "KL"
      ],
      "targetCategories": [
        "housing"
      ]
    },
    "documents": [
      {
        "id": "doc-ration",
        "name": "Ration Card (Non-Priority / Priority BPL)",
        "isMandatory": true,
        "description": "Kerala digital ration card"
      },
      {
        "id": "doc-aadhaar",
        "name": "Aadhaar Card",
        "isMandatory": true,
        "description": "Identity proof of family head and members"
      },
      {
        "id": "doc-income",
        "name": "Village Income Certificate",
        "isMandatory": true,
        "description": "Income certificate from Village Officer showing annual income below \u20b91 Lakh"
      },
      {
        "id": "doc-land",
        "name": "Land Possession Certificate (Thandapper)",
        "isMandatory": true,
        "description": "Proof of owning at least 3-4 cents of land for house construction"
      }
    ],
    "applicationSteps": [
      "Apply online through the LIFE Mission portal (https://lifemission.kerala.gov.in) or Akshaya Centre.",
      "Gram Panchayat / Municipality conducts physical field verification of dwelling.",
      "Once approved in the beneficiary list, agreement is executed and funds released in 4 stages."
    ],
    "applicationUrl": "https://lifemission.kerala.gov.in",
    "offlineApplicationCenter": "Grama Panchayat / Municipality Office / Akshaya Centre",
    "officialSource": "https://lifemission.kerala.gov.in",
    "lastVerified": "2026-09-01",
    "verifiedStatus": "VERIFIED_OFFICIAL"
  },
  {
    "id": "kl-kasp-health",
    "name": "Karunya Arogya Suraksha Padhathi (KASP)",
    "nativeName": "\u0d15\u0d3e\u0d30\u0d41\u0d23\u0d4d\u0d2f \u0d06\u0d30\u0d4b\u0d17\u0d4d\u0d2f \u0d38\u0d41\u0d30\u0d15\u0d4d\u0d37\u0d3e \u0d2a\u0d26\u0d4d\u0d27\u0d24\u0d3f (KASP)",
    "authority": "State Health Agency (SHA), Government of Kerala",
    "department": "Health and Family Welfare Kerala",
    "schemeType": "state",
    "stateId": "KL",
    "state": "Kerala",
    "category": "health",
    "summarySimple": "Cashless health insurance coverage up to \u20b95,00,000 per family per year for secondary and tertiary healthcare in Kerala.",
    "benefits": {
      "amount": "\u20b95,00,000 / year",
      "frequency": "Cashless hospitalization per family per year",
      "type": "insurance",
      "shortSummary": "\u20b95 Lakh annual cashless treatment in empaneled hospitals across Kerala",
      "detailedBenefit": "Provides cashless hospitalization, day-care treatments, and ICU support for economically vulnerable families in Kerala."
    },
    "eligibility": {
      "maxAnnualIncome": 300000,
      "applicableStates": [
        "KL"
      ],
      "targetCategories": [
        "health"
      ]
    },
    "documents": [
      {
        "id": "doc-ration",
        "name": "Kerala Ration Card (Pink / Yellow Priority)",
        "isMandatory": true,
        "description": "Priority ration card issued by Civil Supplies Department"
      },
      {
        "id": "doc-aadhaar",
        "name": "Aadhaar Card",
        "isMandatory": true,
        "description": "Aadhaar cards of all family members"
      }
    ],
    "applicationSteps": [
      "Visit your nearest Akshaya Centre or empaneled hospital KASP help desk.",
      "Present your Ration Card and Aadhaar Card to verify inclusion in the SECC / Priority list.",
      "Obtain your digital KASP e-Card for cashless admissions."
    ],
    "applicationUrl": "https://sha.kerala.gov.in",
    "offlineApplicationCenter": "Empaneled Hospital KASP Helpdesk / Akshaya Centre",
    "officialSource": "https://sha.kerala.gov.in",
    "lastVerified": "2026-09-01",
    "verifiedStatus": "VERIFIED_OFFICIAL"
  },
  {
    "id": "kl-subhiksha-keralam",
    "name": "Subhiksha Keralam Integrated Agriculture Scheme",
    "nativeName": "\u0d38\u0d41\u0d2d\u0d3f\u0d15\u0d4d\u0d37 \u0d15\u0d47\u0d30\u0d33\u0d02 \u0d2a\u0d26\u0d4d\u0d27\u0d24\u0d3f",
    "authority": "Department of Agriculture Development and Farmers' Welfare",
    "department": "Agriculture Kerala",
    "schemeType": "state",
    "stateId": "KL",
    "state": "Kerala",
    "category": "agriculture",
    "summarySimple": "Input subsidies, seed grants, and financial incentives for fallow land cultivation, vegetable farming, and dairy development in Kerala.",
    "benefits": {
      "amount": "Up to \u20b940,000 / hectare subsidy",
      "frequency": "Crop-season based input and cultivation incentive",
      "type": "subsidy",
      "shortSummary": "Subsidies for vegetable farming, fallow land cultivation, and irrigation",
      "detailedBenefit": "Offers free high-yield seeds, solar fencing subsidies, mechanized tools, and interest-free crop loans through primary agricultural credit societies."
    },
    "eligibility": {
      "allowedOccupations": [
        "farmer",
        "agriculture",
        "worker"
      ],
      "applicableStates": [
        "KL"
      ],
      "targetCategories": [
        "agriculture"
      ]
    },
    "documents": [
      {
        "id": "doc-land",
        "name": "Land Tax Receipt / Lease Deed",
        "isMandatory": true,
        "description": "Proof of agricultural land ownership or authorized lease"
      },
      {
        "id": "doc-aadhaar",
        "name": "Aadhaar Card",
        "isMandatory": true,
        "description": "Applicant identification"
      },
      {
        "id": "doc-bank",
        "name": "Bank Passbook",
        "isMandatory": true,
        "description": "Cooperative / Nationalized Bank account details"
      }
    ],
    "applicationSteps": [
      "Visit the AIMS portal (https://www.aims.kerala.gov.in) or visit your local Krishi Bhavan.",
      "Register your land details and crop plan with the Agricultural Officer.",
      "Inspect and receive sanctioned subsidies directly in your bank account."
    ],
    "applicationUrl": "https://www.aims.kerala.gov.in",
    "offlineApplicationCenter": "Local Krishi Bhavan / Agricultural Field Officer",
    "officialSource": "https://www.aims.kerala.gov.in",
    "lastVerified": "2026-09-01",
    "verifiedStatus": "VERIFIED_OFFICIAL"
  },
  {
    "id": "kl-aaswasakiranam",
    "name": "Aaswasakiranam Caregiver Financial Support",
    "nativeName": "\u0d06\u0d36\u0d4d\u0d35\u0d3e\u0d38\u0d15\u0d3f\u0d30\u0d23\u0d02 \u0d2a\u0d26\u0d4d\u0d27\u0d24\u0d3f",
    "authority": "Kerala Social Security Mission (KSSM)",
    "department": "Social Justice Kerala",
    "schemeType": "state",
    "stateId": "KL",
    "state": "Kerala",
    "category": "disability",
    "summarySimple": "Monthly financial assistance of \u20b9600 for primary caregivers of bedridden and severely mentally/physically challenged patients who cannot undertake employment.",
    "benefits": {
      "amount": "\u20b9600 / month",
      "frequency": "Monthly pension assistance to designated caregiver",
      "type": "pension",
      "shortSummary": "\u20b9600 monthly pension for caregivers of bedridden and disabled persons",
      "detailedBenefit": "Provides financial relief to selfless caregivers who have to forego outside employment to take full-time care of critically ill or severely disabled family members."
    },
    "eligibility": {
      "requiresDisability": true,
      "maxAnnualIncome": 100000,
      "applicableStates": [
        "KL"
      ],
      "targetCategories": [
        "disability",
        "financial"
      ]
    },
    "documents": [
      {
        "id": "doc-med-cert",
        "name": "Medical Board Disability Certificate",
        "isMandatory": true,
        "description": "Certificate showing 40%+ permanent disability or bedridden medical state"
      },
      {
        "id": "doc-ration",
        "name": "BPL Ration Card / Income Certificate",
        "isMandatory": true,
        "description": "Proof of economic status"
      },
      {
        "id": "doc-aadhaar",
        "name": "Aadhaar Card of Patient & Caregiver",
        "isMandatory": true,
        "description": "Identification of both caregiver and beneficiary"
      },
      {
        "id": "doc-bank",
        "name": "Caregiver Bank Passbook",
        "isMandatory": true,
        "description": "Bank account where monthly pension will be credited"
      }
    ],
    "applicationSteps": [
      "Download application form from Kerala Social Security Mission (http://socialsecuritymission.gov.in).",
      "Get medical endorsement from Government Medical Officer.",
      "Submit to the Child Development Project Officer (CDPO) or District Social Justice Officer."
    ],
    "applicationUrl": "http://socialsecuritymission.gov.in",
    "offlineApplicationCenter": "CDPO Office / ICDS Project Office / Akshaya Centre",
    "officialSource": "http://socialsecuritymission.gov.in",
    "lastVerified": "2026-09-01",
    "verifiedStatus": "VERIFIED_OFFICIAL"
  }
];

export default ALL_INDIA_SCHEMES;
